/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package costo_por_proceso;

/**
 *
 * @author ASUS
 */
public class CosteoPorProcesoFrame extends javax.swing.JFrame {

    Departamento departamento;
    String nombre;
    Unidad unidadesTerminadas;
    Unidad unidadesIniciadas;
    Costo costoInicial,costoFinal;
    Unidad uep_inicial;
    Unidad uep_final;
    
    
    Costo costoUnidad;
    public CosteoPorProcesoFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtCostoIniciaMaterial = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtUnidadesTerminadas = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtCostoFinalMaterial = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtUepFinal = new javax.swing.JTextField();
        txtUepInicial = new javax.swing.JTextField();
        btnIngresar = new javax.swing.JButton();
        txtCostoFinalCC = new javax.swing.JTextField();
        txtCostoInicialCC = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtTerminadasTasaCM = new javax.swing.JTextField();
        txtTerminadasTasaCC = new javax.swing.JTextField();
        txtTasaUEPInicialCM = new javax.swing.JTextField();
        txtTasaUEPFinalCM = new javax.swing.JTextField();
        txtTasaUEPInicialCC = new javax.swing.JTextField();
        txtTasaUEPFinalCC = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        cbMetodoSolucion = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lbCostoContabilizar = new javax.swing.JLabel();
        lbCostosEUCC = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        lbCostoContabilizado = new javax.swing.JLabel();
        lbCostoContabilizado2 = new javax.swing.JLabel();
        lbTotalCosteado = new javax.swing.JLabel();
        lbTotalUComenzadas = new javax.swing.JLabel();
        lbCostosConversion = new javax.swing.JLabel();
        lbCostContabM = new javax.swing.JLabel();
        lbCostContabCC = new javax.swing.JLabel();
        lbCostosEUMaterial = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnCalcular = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("DATOS DEL DEPARTAMENTO");

        jLabel3.setText("NOMBRE");

        txtCostoIniciaMaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCostoIniciaMaterialActionPerformed(evt);
            }
        });

        jLabel4.setText("Unidades Terminadas");

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });

        txtUnidadesTerminadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUnidadesTerminadasActionPerformed(evt);
            }
        });

        jLabel6.setText("Costo Final");

        jLabel7.setText("Costo Inicial");

        txtCostoFinalMaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCostoFinalMaterialActionPerformed(evt);
            }
        });

        jLabel8.setText("Unidades en proceso Inicial");

        jLabel9.setText("Unidades en proceso Final");

        txtUepFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUepFinalActionPerformed(evt);
            }
        });

        txtUepInicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUepInicialActionPerformed(evt);
            }
        });

        btnIngresar.setText("INGRESAR");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });

        txtCostoFinalCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCostoFinalCCActionPerformed(evt);
            }
        });

        txtCostoInicialCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCostoInicialCCActionPerformed(evt);
            }
        });

        jLabel14.setText("     CM           CC     ");

        txtTerminadasTasaCM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTerminadasTasaCMActionPerformed(evt);
            }
        });

        txtTerminadasTasaCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTerminadasTasaCCActionPerformed(evt);
            }
        });

        txtTasaUEPInicialCM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTasaUEPInicialCMActionPerformed(evt);
            }
        });

        txtTasaUEPFinalCM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTasaUEPFinalCMActionPerformed(evt);
            }
        });

        txtTasaUEPInicialCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTasaUEPInicialCCActionPerformed(evt);
            }
        });

        txtTasaUEPFinalCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTasaUEPFinalCCActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addComponent(jLabel2))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel3)
                .addGap(12, 12, 12)
                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel4)
                .addGap(6, 6, 6)
                .addComponent(txtUnidadesTerminadas, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(txtTerminadasTasaCM, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(txtTerminadasTasaCC, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel8)
                .addGap(6, 6, 6)
                .addComponent(txtUepInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(txtTasaUEPInicialCM, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(txtTasaUEPInicialCC, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel9)
                .addGap(13, 13, 13)
                .addComponent(txtUepFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(txtTasaUEPFinalCM, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(txtTasaUEPFinalCC, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel7)
                .addGap(43, 43, 43)
                .addComponent(txtCostoIniciaMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addComponent(txtCostoInicialCC, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel6)
                .addGap(46, 46, 46)
                .addComponent(txtCostoFinalMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addComponent(txtCostoFinalCC, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addComponent(btnIngresar))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel2)
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel3))
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel14)))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel4))
                    .addComponent(txtUnidadesTerminadas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTerminadasTasaCM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTerminadasTasaCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(80, 80, 80)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel8))
                    .addComponent(txtUepInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(txtTasaUEPInicialCM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(txtTasaUEPInicialCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel9))
                    .addComponent(txtUepFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTasaUEPFinalCM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTasaUEPFinalCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(txtCostoIniciaMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6)
                .addComponent(txtCostoInicialCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(txtCostoFinalMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addComponent(txtCostoFinalCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(btnIngresar))
        );

        cbMetodoSolucion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PEPS", "PP" }));

        jLabel10.setText("RESULTADOS");

        jLabel11.setText("METODO DE SOLUCIÓN");

        jLabel12.setText("COSTO POR CONTABILIZAR");

        jLabel13.setText("COSTO CONTABILIZADO");

        jLabel15.setText("TOTAL U. EQUI- MATERIALES");

        jLabel16.setText("TOTAL UNID COMENZADAS");

        jLabel17.setText("UNID. DE COSTOS DE CONVERSION");

        jLabel18.setText("COSTOS CONTAB. MATERIALES :");

        jLabel19.setText("COSTOS CONTAB. CONVERSION:");

        jLabel20.setText("COSTOS E/U MATERIAL:");

        jLabel21.setText("COSTOS E/U CC:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel11)
                .addGap(32, 32, 32)
                .addComponent(cbMetodoSolucion, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addComponent(lbCostoContabilizar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel13)
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbCostoContabilizado2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbCostoContabilizado, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addComponent(jLabel15)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(lbTotalCosteado, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel16)
                .addGap(21, 21, 21)
                .addComponent(lbTotalUComenzadas, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel17)
                .addGap(8, 8, 8)
                .addComponent(lbCostosConversion, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel18)
                .addGap(5, 5, 5)
                .addComponent(lbCostContabM, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel19)
                .addGap(3, 3, 3)
                .addComponent(lbCostContabCC, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel20)
                .addGap(18, 18, 18)
                .addComponent(lbCostosEUMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel21)
                .addGap(51, 51, 51)
                .addComponent(lbCostosEUCC, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel10)
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel11))
                    .addComponent(cbMetodoSolucion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel12))
                    .addComponent(lbCostoContabilizar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel13))
                    .addComponent(lbCostoContabilizado2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbCostoContabilizado, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(lbTotalCosteado, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel16))
                    .addComponent(lbTotalUComenzadas, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLabel17))
                    .addComponent(lbCostosConversion, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel18))
                    .addComponent(lbCostContabM, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel19))
                    .addComponent(lbCostContabCC, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel20))
                    .addComponent(lbCostosEUMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(lbCostosEUCC, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        jLabel1.setText("ANALIZANDO  LOS COSTOS DEL PROCESO DE PRODUCCIÓN DE UN DEPARTAMENTO");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(jLabel1))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel1))
        );

        btnCalcular.setText("CALCULAR");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(btnCalcular))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(btnCalcular))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCostoIniciaMaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCostoIniciaMaterialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCostoIniciaMaterialActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtUnidadesTerminadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUnidadesTerminadasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUnidadesTerminadasActionPerformed

    private void txtCostoFinalMaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCostoFinalMaterialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCostoFinalMaterialActionPerformed

    private void txtUepFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUepFinalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUepFinalActionPerformed

    private void txtUepInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUepInicialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUepInicialActionPerformed

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        
            nombre = txtNombre.getText();
            
            
            unidadesTerminadas = new Unidad(
                    Double.parseDouble(txtTerminadasTasaCC.getText()),
                    Double.parseDouble(txtTerminadasTasaCM.getText()),
                    costoUnidad = new Costo(0,0),
                    Integer.parseInt(txtUnidadesTerminadas.getText()),
                    "TERMINADO"
            );
            
                uep_inicial = new Unidad(
                    Double.parseDouble(txtTasaUEPInicialCC.getText()),
                    Double.parseDouble(txtTasaUEPInicialCM.getText()),
                    costoUnidad = new Costo(0,0),
                    Integer.parseInt(txtUepInicial.getText()),
                    "UEP/INICIAL"
            );
                
                                uep_final = new Unidad(
                    Double.parseDouble(txtTasaUEPFinalCC.getText()),
                    Double.parseDouble(txtTasaUEPFinalCM.getText()),
                    costoUnidad = new Costo(0,0),
                    Integer.parseInt(txtUepFinal.getText()),
                    "UEP/FINAL"
            );
                                
                                
           costoFinal = new Costo(
                   Double.parseDouble(txtCostoFinalMaterial.getText()),
                   Double.parseDouble(txtCostoFinalCC.getText()));
                   
                                
           costoInicial = new Costo(
                   Double.parseDouble(txtCostoIniciaMaterial.getText()),
                   Double.parseDouble(txtCostoInicialCC.getText()));
                   
           
           
        
        
     departamento = new Departamento(nombre, unidadesTerminadas, unidadesIniciadas, costoInicial, costoFinal, uep_inicial, uep_final);
        
        
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_btnIngresarActionPerformed

    private void txtCostoFinalCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCostoFinalCCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCostoFinalCCActionPerformed

    private void txtCostoInicialCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCostoInicialCCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCostoInicialCCActionPerformed

    private void txtTerminadasTasaCMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTerminadasTasaCMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTerminadasTasaCMActionPerformed

    private void txtTerminadasTasaCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTerminadasTasaCCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTerminadasTasaCCActionPerformed

    private void txtTasaUEPInicialCMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTasaUEPInicialCMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTasaUEPInicialCMActionPerformed

    private void txtTasaUEPFinalCMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTasaUEPFinalCMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTasaUEPFinalCMActionPerformed

    private void txtTasaUEPInicialCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTasaUEPInicialCCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTasaUEPInicialCCActionPerformed

    private void txtTasaUEPFinalCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTasaUEPFinalCCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTasaUEPFinalCCActionPerformed

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        if(cbMetodoSolucion.getSelectedIndex()==0)
        {
            departamento.procesandoInformacion(true);
            lbCostosEUMaterial.setText(departamento.costoE_porUnidadMaterial(true)+"");
            lbCostosEUCC.setText(departamento.costoE_porUnidadCC(true)+"");
            
            lbCostContabCC.setText(costoFinal.costoConversion+"");
            lbCostContabM.setText(costoFinal.costoMaterial+"");
            
        } else {
            
            departamento.procesandoInformacion(false);
            lbCostosEUMaterial.setText(departamento.costoE_porUnidadMaterial(false)+"");
            lbCostosEUCC.setText(departamento.costoE_porUnidadCC(false)+"");
            
            lbCostContabM.setText(departamento.costosContabilizarMateriales()+"");
            lbCostContabCC.setText(departamento.costosContabilizarCC()+"");
        }
        
        
            lbTotalCosteado.setText(departamento.totalCosteado+"");
            lbTotalUComenzadas.setText(departamento.unidades_comenzadas()+"");
            lbCostosConversion.setText(departamento.ueCConversion+"");

            
            
            
            lbCostoContabilizar.setText(departamento.costoContabilizar+"");
            lbCostoContabilizado.setText(departamento.costoContabilizado+"");
    }//GEN-LAST:event_btnCalcularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CosteoPorProcesoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CosteoPorProcesoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CosteoPorProcesoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CosteoPorProcesoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CosteoPorProcesoFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnIngresar;
    private javax.swing.JComboBox<String> cbMetodoSolucion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lbCostContabCC;
    private javax.swing.JLabel lbCostContabM;
    private javax.swing.JLabel lbCostoContabilizado;
    private javax.swing.JLabel lbCostoContabilizado2;
    private javax.swing.JLabel lbCostoContabilizar;
    private javax.swing.JLabel lbCostosConversion;
    private javax.swing.JLabel lbCostosEUCC;
    private javax.swing.JLabel lbCostosEUMaterial;
    private javax.swing.JLabel lbTotalCosteado;
    private javax.swing.JLabel lbTotalUComenzadas;
    private javax.swing.JTextField txtCostoFinalCC;
    private javax.swing.JTextField txtCostoFinalMaterial;
    private javax.swing.JTextField txtCostoIniciaMaterial;
    private javax.swing.JTextField txtCostoInicialCC;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTasaUEPFinalCC;
    private javax.swing.JTextField txtTasaUEPFinalCM;
    private javax.swing.JTextField txtTasaUEPInicialCC;
    private javax.swing.JTextField txtTasaUEPInicialCM;
    private javax.swing.JTextField txtTerminadasTasaCC;
    private javax.swing.JTextField txtTerminadasTasaCM;
    private javax.swing.JTextField txtUepFinal;
    private javax.swing.JTextField txtUepInicial;
    private javax.swing.JTextField txtUnidadesTerminadas;
    // End of variables declaration//GEN-END:variables
}
