/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package costo_por_proceso;

/**
 *
 * @author ASUS
 */
public class CosteoPorProcesoFrame extends javax.swing.JFrame {

    Departamento departamento;
    String nombre;
    Unidad unidadesTerminadas;
    Unidad unidadesIniciadas;
    Costo costoInicial,costoFinal;
    Unidad uep_inicial;
    Unidad uep_final;
    
    
    Costo costoUnidad;
    public CosteoPorProcesoFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtCostoIniciaMaterial = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtUnidadesTerminadas = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtCostoFinalMaterial = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtUepFinal = new javax.swing.JTextField();
        txtUepInicial = new javax.swing.JTextField();
        btnIngresar = new javax.swing.JButton();
        txtCostoFinalCC = new javax.swing.JTextField();
        txtCostoInicialCC = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtTerminadasTasaCM = new javax.swing.JTextField();
        txtUEPFinalCosto = new javax.swing.JTextField();
        txtTerminadasTasaCC = new javax.swing.JTextField();
        txtTerminadaCosto = new javax.swing.JTextField();
        txtTasaUEPInicialCM = new javax.swing.JTextField();
        txtTasaUEPFinalCM = new javax.swing.JTextField();
        txtTasaUEPInicialCC = new javax.swing.JTextField();
        txtTasaUEPFinalCC = new javax.swing.JTextField();
        txtUEPInicialCosto = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        cbMetodoSolucion = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lbCostoContabilizar = new javax.swing.JLabel();
        lbCostosEUCC = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        lbCostoContabilizado = new javax.swing.JLabel();
        lbCostoContabilizado2 = new javax.swing.JLabel();
        lbTotalCosteado = new javax.swing.JLabel();
        lbTotalUComenzadas = new javax.swing.JLabel();
        lbCostosConversion = new javax.swing.JLabel();
        lbCostContabM = new javax.swing.JLabel();
        lbCostContabCC = new javax.swing.JLabel();
        lbCostosEUMaterial = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnCalcular = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("DATOS DEL DEPARTAMENTO");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 30, -1, -1));

        jLabel3.setText("NOMBRE");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 73, -1, -1));

        txtCostoIniciaMaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCostoIniciaMaterialActionPerformed(evt);
            }
        });
        jPanel1.add(txtCostoIniciaMaterial, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 369, 135, -1));

        jLabel4.setText("Unidades Terminadas");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 115, -1, -1));

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 69, 135, -1));

        txtUnidadesTerminadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUnidadesTerminadasActionPerformed(evt);
            }
        });
        jPanel1.add(txtUnidadesTerminadas, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 111, 135, -1));

        jLabel6.setText("Costo Final");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 443, -1, -1));

        jLabel7.setText("Costo Inicial");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 349, -1, -1));

        txtCostoFinalMaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCostoFinalMaterialActionPerformed(evt);
            }
        });
        jPanel1.add(txtCostoFinalMaterial, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 435, 135, -1));

        jLabel8.setText("Unidades en proceso Inicial");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 219, -1, -1));

        jLabel9.setText("Unidades en proceso Final");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 261, -1, -1));

        txtUepFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUepFinalActionPerformed(evt);
            }
        });
        jPanel1.add(txtUepFinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, 100, -1));

        txtUepInicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUepInicialActionPerformed(evt);
            }
        });
        jPanel1.add(txtUepInicial, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 215, 100, -1));

        btnIngresar.setText("INGRESAR");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });
        jPanel1.add(btnIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 500, -1, -1));

        txtCostoFinalCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCostoFinalCCActionPerformed(evt);
            }
        });
        jPanel1.add(txtCostoFinalCC, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 464, 135, -1));

        txtCostoInicialCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCostoInicialCCActionPerformed(evt);
            }
        });
        jPanel1.add(txtCostoInicialCC, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 399, 135, -1));

        jLabel14.setText("TASA      CM           CC            COSTO");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(241, 77, 219, -1));

        txtTerminadasTasaCM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTerminadasTasaCMActionPerformed(evt);
            }
        });
        jPanel1.add(txtTerminadasTasaCM, new org.netbeans.lib.awtextra.AbsoluteConstraints(276, 111, 48, -1));

        txtUEPFinalCosto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUEPFinalCostoActionPerformed(evt);
            }
        });
        jPanel1.add(txtUEPFinalCosto, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 260, 70, -1));

        txtTerminadasTasaCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTerminadasTasaCCActionPerformed(evt);
            }
        });
        jPanel1.add(txtTerminadasTasaCC, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 111, 48, -1));

        txtTerminadaCosto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTerminadaCostoActionPerformed(evt);
            }
        });
        jPanel1.add(txtTerminadaCosto, new org.netbeans.lib.awtextra.AbsoluteConstraints(396, 111, 64, -1));

        txtTasaUEPInicialCM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTasaUEPInicialCMActionPerformed(evt);
            }
        });
        jPanel1.add(txtTasaUEPInicialCM, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 220, 48, -1));

        txtTasaUEPFinalCM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTasaUEPFinalCMActionPerformed(evt);
            }
        });
        jPanel1.add(txtTasaUEPFinalCM, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 260, 48, -1));

        txtTasaUEPInicialCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTasaUEPInicialCCActionPerformed(evt);
            }
        });
        jPanel1.add(txtTasaUEPInicialCC, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 220, 48, -1));

        txtTasaUEPFinalCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTasaUEPFinalCCActionPerformed(evt);
            }
        });
        jPanel1.add(txtTasaUEPFinalCC, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 260, 48, -1));

        txtUEPInicialCosto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUEPInicialCostoActionPerformed(evt);
            }
        });
        jPanel1.add(txtUEPInicialCosto, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 220, 70, -1));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cbMetodoSolucion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PEPS", "PP" }));
        jPanel2.add(cbMetodoSolucion, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 79, -1));

        jLabel10.setText("RESULTADOS");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 32, 92, -1));

        jLabel11.setText("METODO DE SOLUCIÓN");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 76, -1, -1));

        jLabel12.setText("COSTO POR CONTABILIZAR");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 147, -1, -1));

        jLabel13.setText("COSTO CONTABILIZADO");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 212, -1, -1));
        jPanel2.add(lbCostoContabilizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 138, 120, 25));
        jPanel2.add(lbCostosEUCC, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 470, 140, 24));

        jLabel15.setText("TOTAL COSTEADO");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, -1, -1));

        jLabel16.setText("TOTAL UNID COMENZADAS");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 313, -1, -1));

        jLabel17.setText("COSTOS DE CONVERSION");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 347, -1, -1));

        jLabel18.setText("COSTOS CONTAB. MATERIALES :");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 381, -1, -1));

        jLabel19.setText("COSTOS CONTAB. CONVERSION:");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 415, -1, -1));

        jLabel20.setText("COSTOS E/U MATERIAL:");
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 443, -1, -1));

        jLabel21.setText("COSTOS E/U CC:");
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 469, -1, -1));
        jPanel2.add(lbCostoContabilizado, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 140, 30));
        jPanel2.add(lbCostoContabilizado2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 140, 30));
        jPanel2.add(lbTotalCosteado, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, 140, 24));
        jPanel2.add(lbTotalUComenzadas, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 310, 140, 24));
        jPanel2.add(lbCostosConversion, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 340, 140, 24));
        jPanel2.add(lbCostContabM, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 380, 140, 24));
        jPanel2.add(lbCostContabCC, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 410, 140, 24));
        jPanel2.add(lbCostosEUMaterial, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 440, 140, 24));

        jLabel1.setText("ANALIZANDO  LOS COSTOS DEL PROCESO DE PRODUCCIÓN DE UN DEPARTAMENTO");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(jLabel1)
                .addContainerGap(140, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel1)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        btnCalcular.setText("CALCULAR");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(103, 103, 103)
                                .addComponent(btnCalcular)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 592, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCalcular)
                        .addGap(38, 38, 38)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCostoIniciaMaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCostoIniciaMaterialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCostoIniciaMaterialActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtUnidadesTerminadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUnidadesTerminadasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUnidadesTerminadasActionPerformed

    private void txtCostoFinalMaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCostoFinalMaterialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCostoFinalMaterialActionPerformed

    private void txtUepFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUepFinalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUepFinalActionPerformed

    private void txtUepInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUepInicialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUepInicialActionPerformed

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        
            nombre = txtNombre.getText();
            
            
            unidadesTerminadas = new Unidad(
                    Double.parseDouble(txtTerminadasTasaCC.getText()),
                    Double.parseDouble(txtTerminadasTasaCM.getText()),
                    costoUnidad = new Costo(0,0),
                    Integer.parseInt(txtUnidadesTerminadas.getText()),
                    "TERMINADO"
            );
            
                uep_inicial = new Unidad(
                    Double.parseDouble(txtTasaUEPInicialCC.getText()),
                    Double.parseDouble(txtTasaUEPInicialCM.getText()),
                    costoUnidad = new Costo(0,0),
                    Integer.parseInt(txtUepInicial.getText()),
                    "UEP/INICIAL"
            );
                
                                uep_final = new Unidad(
                    Double.parseDouble(txtTasaUEPFinalCC.getText()),
                    Double.parseDouble(txtTasaUEPFinalCM.getText()),
                    costoUnidad = new Costo(0,0),
                    Integer.parseInt(txtUepFinal.getText()),
                    "UEP/FINAL"
            );
                                
                                
           costoFinal = new Costo(
                   Double.parseDouble(txtCostoFinalMaterial.getText()),
                   Double.parseDouble(txtCostoFinalCC.getText()));
                   
                                
           costoInicial = new Costo(
                   Double.parseDouble(txtCostoIniciaMaterial.getText()),
                   Double.parseDouble(txtCostoInicialCC.getText()));
                   
           
           
        
        
     departamento = new Departamento(nombre, unidadesTerminadas, unidadesIniciadas, costoInicial, costoFinal, uep_inicial, uep_final);
        
        
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_btnIngresarActionPerformed

    private void txtCostoFinalCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCostoFinalCCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCostoFinalCCActionPerformed

    private void txtCostoInicialCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCostoInicialCCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCostoInicialCCActionPerformed

    private void txtTerminadasTasaCMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTerminadasTasaCMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTerminadasTasaCMActionPerformed

    private void txtUEPFinalCostoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUEPFinalCostoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUEPFinalCostoActionPerformed

    private void txtTerminadasTasaCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTerminadasTasaCCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTerminadasTasaCCActionPerformed

    private void txtTerminadaCostoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTerminadaCostoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTerminadaCostoActionPerformed

    private void txtTasaUEPInicialCMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTasaUEPInicialCMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTasaUEPInicialCMActionPerformed

    private void txtTasaUEPFinalCMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTasaUEPFinalCMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTasaUEPFinalCMActionPerformed

    private void txtTasaUEPInicialCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTasaUEPInicialCCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTasaUEPInicialCCActionPerformed

    private void txtTasaUEPFinalCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTasaUEPFinalCCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTasaUEPFinalCCActionPerformed

    private void txtUEPInicialCostoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUEPInicialCostoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUEPInicialCostoActionPerformed

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        if(cbMetodoSolucion.getSelectedIndex()==0)
        {
            departamento.procesandoInformacion(true);
            lbCostosEUMaterial.setText(departamento.costoE_porUnidadMaterial(true)+"");
            lbCostosEUCC.setText(departamento.costoE_porUnidadCC(true)+"");
            
        } else {
            
            lbCostosEUMaterial.setText(departamento.costoE_porUnidadMaterial(false)+"");
            departamento.procesandoInformacion(false);
            lbCostosEUCC.setText(departamento.costoE_porUnidadCC(false)+"");
        }
        
        
            lbTotalCosteado.setText(departamento.totalCosteado+"");
            lbTotalUComenzadas.setText(departamento.unidades_comenzadas()+"");
            lbCostosConversion.setText(departamento.ueCConversion+"");
            lbCostContabM.setText(departamento.costosContabilizarMateriales()+"");
            lbCostContabCC.setText(departamento.costosContabilizarCC()+"");
            lbCostosEUCC.setText(departamento.costoContabilizado+"");
            
            
            lbCostoContabilizar.setText(departamento.costoContabilizar+"");
            lbCostoContabilizado.setText(departamento.costoContabilizado+"");
    }//GEN-LAST:event_btnCalcularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CosteoPorProcesoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CosteoPorProcesoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CosteoPorProcesoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CosteoPorProcesoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CosteoPorProcesoFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnIngresar;
    private javax.swing.JComboBox<String> cbMetodoSolucion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lbCostContabCC;
    private javax.swing.JLabel lbCostContabM;
    private javax.swing.JLabel lbCostoContabilizado;
    private javax.swing.JLabel lbCostoContabilizado2;
    private javax.swing.JLabel lbCostoContabilizar;
    private javax.swing.JLabel lbCostosConversion;
    private javax.swing.JLabel lbCostosEUCC;
    private javax.swing.JLabel lbCostosEUMaterial;
    private javax.swing.JLabel lbTotalCosteado;
    private javax.swing.JLabel lbTotalUComenzadas;
    private javax.swing.JTextField txtCostoFinalCC;
    private javax.swing.JTextField txtCostoFinalMaterial;
    private javax.swing.JTextField txtCostoIniciaMaterial;
    private javax.swing.JTextField txtCostoInicialCC;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTasaUEPFinalCC;
    private javax.swing.JTextField txtTasaUEPFinalCM;
    private javax.swing.JTextField txtTasaUEPInicialCC;
    private javax.swing.JTextField txtTasaUEPInicialCM;
    private javax.swing.JTextField txtTerminadaCosto;
    private javax.swing.JTextField txtTerminadasTasaCC;
    private javax.swing.JTextField txtTerminadasTasaCM;
    private javax.swing.JTextField txtUEPFinalCosto;
    private javax.swing.JTextField txtUEPInicialCosto;
    private javax.swing.JTextField txtUepFinal;
    private javax.swing.JTextField txtUepInicial;
    private javax.swing.JTextField txtUnidadesTerminadas;
    // End of variables declaration//GEN-END:variables
}
