package Costeo_ABC;

import Costeo_ABC.Actividad;
import Costeo_ABC.Impulsador;
import Costeo_ABC.Proceso;
import java.util.ArrayList;



/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */



/**
 *
 * @author Usuario
 */
public class Costeo_ABC extends javax.swing.JFrame {

    ArrayList<Actividad> actividadesTotales=new ArrayList();
    ArrayList<Actividad> actividades=new ArrayList();
    ArrayList<Impulsador> impulsadores=new ArrayList();
    
    ArrayList<Proceso> proceso=new ArrayList();
    
    
    public Costeo_ABC() {
        initComponents();
        jp_panelProducto.setVisible(false);
        bt_calcular.setVisible(false);
        cb_impulsadorUsado.setEnabled(false);
        bt_reporte.setVisible(false);
        jPanel2.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        txt_actividadNom = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_actividadCif = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_impulsadorActividad = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_impulsadorActividadCant = new javax.swing.JTextField();
        bt_ingresarActividad = new javax.swing.JButton();
        bt_desblockA = new javax.swing.JButton();
        bt_blockA = new javax.swing.JButton();
        bt_activarProducto = new javax.swing.JButton();
        jp_panelProducto = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        cb_actividadUsada = new javax.swing.JComboBox<>();
        bt_asignarAProducto = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        cb_impulsadorUsado = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        txt_cantidadImpulsadorProducto = new javax.swing.JTextField();
        bt_añadirProducto = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_productoCosMaterial = new javax.swing.JTextField();
        txt_productoNom = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_productoUnidades = new javax.swing.JTextField();
        txt_productoCosManoObra = new javax.swing.JTextField();
        bt_desBlockAsignar = new javax.swing.JButton();
        bt_blockAsignar = new javax.swing.JButton();
        bt_activarCalcular = new javax.swing.JButton();
        bt_calcular = new javax.swing.JButton();
        bt_reporte = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        at_reporte = new javax.swing.JTextArea();
        bt_atras = new javax.swing.JButton();

        jButton2.setText("Block");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 51));
        setMinimumSize(new java.awt.Dimension(834, 515));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(null);

        jLabel1.setText("Actividades");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(330, 10, 80, 16);
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(10, 170, 810, 10);

        jLabel2.setText("Nombre Actividad");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 50, 120, 16);
        jPanel1.add(txt_actividadNom);
        txt_actividadNom.setBounds(140, 40, 240, 30);

        jLabel3.setText("Cif Actividad");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(400, 50, 90, 16);
        jPanel1.add(txt_actividadCif);
        txt_actividadCif.setBounds(500, 40, 140, 30);

        jLabel4.setText("Impulsador nombre");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 100, 130, 16);
        jPanel1.add(txt_impulsadorActividad);
        txt_impulsadorActividad.setBounds(140, 90, 240, 30);

        jLabel5.setText("Numero total");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(400, 100, 100, 16);
        jPanel1.add(txt_impulsadorActividadCant);
        txt_impulsadorActividadCant.setBounds(500, 90, 140, 30);

        bt_ingresarActividad.setText("Ingresar Actividad");
        bt_ingresarActividad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_ingresarActividadActionPerformed(evt);
            }
        });
        jPanel1.add(bt_ingresarActividad);
        bt_ingresarActividad.setBounds(660, 90, 150, 30);

        bt_desblockA.setFont(new java.awt.Font("Tahoma", 1, 8)); // NOI18N
        bt_desblockA.setText("DesBlock");
        bt_desblockA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_desblockAActionPerformed(evt);
            }
        });
        jPanel1.add(bt_desblockA);
        bt_desblockA.setBounds(740, 130, 70, 30);

        bt_blockA.setFont(new java.awt.Font("Tahoma", 1, 8)); // NOI18N
        bt_blockA.setText("Block");
        bt_blockA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_blockAActionPerformed(evt);
            }
        });
        jPanel1.add(bt_blockA);
        bt_blockA.setBounds(660, 130, 70, 30);

        bt_activarProducto.setText("Activar Producto");
        bt_activarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_activarProductoActionPerformed(evt);
            }
        });
        jPanel1.add(bt_activarProducto);
        bt_activarProducto.setBounds(30, 180, 150, 32);

        jp_panelProducto.setLayout(null);

        jLabel10.setText("Actividad Usada");
        jp_panelProducto.add(jLabel10);
        jLabel10.setBounds(20, 20, 100, 16);

        cb_actividadUsada.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONE" }));
        cb_actividadUsada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_actividadUsadaActionPerformed(evt);
            }
        });
        jp_panelProducto.add(cb_actividadUsada);
        cb_actividadUsada.setBounds(160, 10, 250, 30);

        bt_asignarAProducto.setText("Asignar");
        bt_asignarAProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_asignarAProductoActionPerformed(evt);
            }
        });
        jp_panelProducto.add(bt_asignarAProducto);
        bt_asignarAProducto.setBounds(270, 60, 120, 30);

        jLabel11.setText("Impulsador Usado");
        jp_panelProducto.add(jLabel11);
        jLabel11.setBounds(420, 20, 110, 16);

        cb_impulsadorUsado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "------------" }));
        jp_panelProducto.add(cb_impulsadorUsado);
        cb_impulsadorUsado.setBounds(530, 10, 250, 30);

        jLabel12.setText("Cantidad Impulsador");
        jp_panelProducto.add(jLabel12);
        jLabel12.setBounds(20, 70, 120, 16);
        jp_panelProducto.add(txt_cantidadImpulsadorProducto);
        txt_cantidadImpulsadorProducto.setBounds(160, 60, 90, 30);

        bt_añadirProducto.setText("Añadir Producto");
        bt_añadirProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_añadirProductoActionPerformed(evt);
            }
        });
        jp_panelProducto.add(bt_añadirProducto);
        bt_añadirProducto.setBounds(20, 210, 180, 32);

        jLabel6.setText("Nombre Producto");
        jp_panelProducto.add(jLabel6);
        jLabel6.setBounds(20, 120, 110, 16);

        jLabel8.setText("Costo Material");
        jp_panelProducto.add(jLabel8);
        jLabel8.setBounds(20, 170, 90, 16);
        jp_panelProducto.add(txt_productoCosMaterial);
        txt_productoCosMaterial.setBounds(160, 160, 150, 30);
        jp_panelProducto.add(txt_productoNom);
        txt_productoNom.setBounds(160, 110, 250, 30);

        jLabel9.setText("Costo Mano de Obra");
        jp_panelProducto.add(jLabel9);
        jLabel9.setBounds(350, 170, 120, 16);

        jLabel7.setText("Unidades Producto");
        jp_panelProducto.add(jLabel7);
        jLabel7.setBounds(440, 120, 120, 16);
        jp_panelProducto.add(txt_productoUnidades);
        txt_productoUnidades.setBounds(560, 110, 140, 30);
        jp_panelProducto.add(txt_productoCosManoObra);
        txt_productoCosManoObra.setBounds(490, 160, 140, 30);

        bt_desBlockAsignar.setFont(new java.awt.Font("Tahoma", 1, 8)); // NOI18N
        bt_desBlockAsignar.setText("DesBlock");
        bt_desBlockAsignar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_desBlockAsignarActionPerformed(evt);
            }
        });
        jp_panelProducto.add(bt_desBlockAsignar);
        bt_desBlockAsignar.setBounds(490, 60, 70, 30);

        bt_blockAsignar.setFont(new java.awt.Font("Tahoma", 1, 8)); // NOI18N
        bt_blockAsignar.setText("Block");
        bt_blockAsignar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_blockAsignarActionPerformed(evt);
            }
        });
        jp_panelProducto.add(bt_blockAsignar);
        bt_blockAsignar.setBounds(410, 60, 70, 30);

        jPanel1.add(jp_panelProducto);
        jp_panelProducto.setBounds(10, 220, 810, 240);

        bt_activarCalcular.setText("Activar Calcular");
        bt_activarCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_activarCalcularActionPerformed(evt);
            }
        });
        jPanel1.add(bt_activarCalcular);
        bt_activarCalcular.setBounds(210, 180, 160, 32);

        bt_calcular.setText("Calcular");
        bt_calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_calcularActionPerformed(evt);
            }
        });
        jPanel1.add(bt_calcular);
        bt_calcular.setBounds(460, 470, 180, 32);

        bt_reporte.setText("Reporte");
        bt_reporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_reporteActionPerformed(evt);
            }
        });
        jPanel1.add(bt_reporte);
        bt_reporte.setBounds(660, 470, 160, 32);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 834;
        gridBagConstraints.ipady = 515;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        getContentPane().add(jPanel1, gridBagConstraints);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setLayout(null);

        at_reporte.setColumns(20);
        at_reporte.setRows(5);
        jScrollPane1.setViewportView(at_reporte);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(10, 10, 810, 400);

        bt_atras.setText("Atras");
        bt_atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_atrasActionPerformed(evt);
            }
        });
        jPanel2.add(bt_atras);
        bt_atras.setBounds(710, 440, 110, 32);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 834;
        gridBagConstraints.ipady = 515;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        getContentPane().add(jPanel2, gridBagConstraints);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bt_ingresarActividadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_ingresarActividadActionPerformed
        String NomActividad,NomImpulsador;
        double CifActividad,CantImpulsador;
        if(!txt_actividadNom.getText().equals("") && !txt_actividadCif.getText().equals("") && !txt_impulsadorActividad.getText().equals("") && !txt_impulsadorActividadCant.getText().equals("")){
            System.out.println("Aviso de Ingreso Actividades:\nActividades con todos los datos\n");
            NomActividad=txt_actividadNom.getText();
            CifActividad=Double.parseDouble(txt_actividadCif.getText());
            NomImpulsador=txt_impulsadorActividad.getText();
            CantImpulsador=Double.parseDouble(txt_impulsadorActividadCant.getText());
            Actividad act=new Actividad(NomActividad, CifActividad, new Impulsador(NomImpulsador, CantImpulsador));
            act.costoUnidadImpulsador();
            actividadesTotales.add(act);
            cb_actividadUsada.addItem(act.getNombreActividad());
            limpiarActividad();
        }else{
            System.out.println("Aviso de Ingreso Actividades:\nfaltan datos de las actividades\n");
            limpiarActividad();
        }
        
    }//GEN-LAST:event_bt_ingresarActividadActionPerformed

    private void bt_blockAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_blockAActionPerformed
        txt_actividadNom.setEditable(false);
        txt_actividadCif.setEditable(false);
        txt_impulsadorActividad.setEditable(false);
        txt_impulsadorActividadCant.setEditable(false);
        bt_ingresarActividad.setEnabled(false);
        
    }//GEN-LAST:event_bt_blockAActionPerformed

    private void bt_desblockAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_desblockAActionPerformed
        txt_actividadNom.setEditable(true);
        txt_actividadCif.setEditable(true);
        txt_impulsadorActividad.setEditable(true);
        txt_impulsadorActividadCant.setEditable(true);
        bt_ingresarActividad.setEnabled(true);
    }//GEN-LAST:event_bt_desblockAActionPerformed

    private void bt_activarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_activarProductoActionPerformed
        jp_panelProducto.setVisible(true);
    }//GEN-LAST:event_bt_activarProductoActionPerformed

    private void bt_activarCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_activarCalcularActionPerformed
        bt_calcular.setVisible(true);
    }//GEN-LAST:event_bt_activarCalcularActionPerformed

    private void cb_actividadUsadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_actividadUsadaActionPerformed
        for(Actividad act : actividadesTotales){
            if(act.getNombreActividad().equalsIgnoreCase(cb_actividadUsada.getSelectedItem().toString())){
                cb_impulsadorUsado.removeAllItems();
                cb_impulsadorUsado.addItem(act.getImpulsador().getNombre());
            }
        }
        
    }//GEN-LAST:event_cb_actividadUsadaActionPerformed

    private void bt_añadirProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_añadirProductoActionPerformed
        String productoNom;
        double costoMaterial,costoManoObra;
        int numeroUnidades;
        if(!txt_productoNom.getText().equals("") && !txt_productoUnidades.getText().equals("") && !txt_productoCosMaterial.getText().equals("") && !txt_productoCosManoObra.getText().equals("")){
            productoNom=txt_productoNom.getText();
            costoManoObra=Double.parseDouble(txt_productoCosManoObra.getText());
            costoMaterial=Double.parseDouble(txt_productoCosMaterial.getText());
            numeroUnidades=Integer.parseInt(txt_productoUnidades.getText());
            Proceso process=new Proceso(costoMaterial, costoManoObra, productoNom, numeroUnidades);
            process.setActividadesUsadas(actividades);
            process.setImpulsadorUsados(impulsadores);
            proceso.add(process);
            limpiarProducto();
            llenarCb_actividadUsada();
            System.out.println("Producto añadido Correctamente");
            actividades=null;
            impulsadores=null;
            actividades=new ArrayList();
            impulsadores=new ArrayList();
        }else{
            limpiarProducto();
            System.out.println("Complete los datos");
        }
        
        
    }//GEN-LAST:event_bt_añadirProductoActionPerformed

    private void bt_asignarAProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_asignarAProductoActionPerformed
        String impulsadorNom;
        double impulsadorCant;
        if(!txt_cantidadImpulsadorProducto.getText().isEmpty() && !cb_actividadUsada.getSelectedItem().equals("SELECCIONE")){
            impulsadorNom=cb_impulsadorUsado.getSelectedItem().toString();
            impulsadorCant=Double.parseDouble(txt_cantidadImpulsadorProducto.getText());
            Impulsador impul=new Impulsador(impulsadorNom,impulsadorCant);
            impulsadores.add(impul);
            for(Actividad act : actividadesTotales){
                if(act.getImpulsador().getNombre().equals(impul.getNombre())){
                    actividades.add(act);
                    cb_actividadUsada.removeItem(act.getNombreActividad());
                    cb_actividadUsada.setSelectedIndex(0);
                    cb_impulsadorUsado.removeAllItems();
                    cb_impulsadorUsado.addItem("-----");
                    cb_impulsadorUsado.setSelectedIndex(0);
                }
            }
            txt_cantidadImpulsadorProducto.setText("");
            
            System.out.println("Asignacion de Actividades al Producto Exitosa");
        }else{
            System.out.println("Complete todos los datos");
        }
        
    }//GEN-LAST:event_bt_asignarAProductoActionPerformed

    private void bt_blockAsignarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_blockAsignarActionPerformed
        cb_actividadUsada.setEnabled(false);
        txt_cantidadImpulsadorProducto.setEditable(false);
        bt_asignarAProducto.setEnabled(false);
    }//GEN-LAST:event_bt_blockAsignarActionPerformed

    private void bt_desBlockAsignarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_desBlockAsignarActionPerformed
        cb_actividadUsada.setEnabled(true);
        txt_cantidadImpulsadorProducto.setEditable(true);
        bt_asignarAProducto.setEnabled(true);
    }//GEN-LAST:event_bt_desBlockAsignarActionPerformed

    private void bt_calcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_calcularActionPerformed
        for(Proceso proc : proceso){
            proc.calculoCifaActividad((a,b)->a.getImpulsador().getNombre().equals(b.getNombre()));
            at_reporte.append("\nDatos del Producto: "+proc.getNombreProducto()+
                    "\n N° Unidades: "+proc.getNumeroUnidades()+"\nCosto MaterialD: "+
                    proc.getCostoMaterialD()+"\nCosto Mano de ObraD: "+proc.getCostoManoObraD());
            
            
            for(int i=0;i<proc.getActividadesUsadas().size();i++){
                at_reporte.append("\nLa actividad "+proc.getActividadesUsadas().get(i).getNombreActividad()+" : "+proc.getActividadesUsadas().get(i).getCostoUnidadImpulsador()+" X "+proc.getImpulsadorUsados().get(i).getCantidad()+" = "+proc.getCifaActividad().get(i)+"\n");
            }
            at_reporte.append("\nEl cifa total es: "+proc.calculoCifaTotal()+"\n");
            
            at_reporte.append("El costo total del producto es: "+proc.calculoCostoTotal()+"\n");
            at_reporte.append("El costo unitario del producto es: "+proc.calculoCostoUnitario()+"\n");
            at_reporte.append("--------------------------------------------------------");
        }
        
        
        bt_reporte.setVisible(true);
    }//GEN-LAST:event_bt_calcularActionPerformed

    private void bt_reporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_reporteActionPerformed
        jPanel2.setVisible(true);
        jPanel1.setVisible(false);
    }//GEN-LAST:event_bt_reporteActionPerformed

    private void bt_atrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_atrasActionPerformed
        jPanel2.setVisible(false);
        jPanel1.setVisible(true);
    }//GEN-LAST:event_bt_atrasActionPerformed

    private void limpiarActividad(){
        txt_actividadNom.setText("");
        txt_actividadCif.setText("");
        txt_impulsadorActividad.setText("");
        txt_impulsadorActividadCant.setText("");
    }
    
    private void limpiarProducto(){
        txt_productoNom.setText("");
        txt_productoUnidades.setText("");
        txt_productoCosMaterial.setText("");
        txt_productoCosManoObra.setText("");
    }
    
    private void llenarCb_actividadUsada(){
        int num=cb_actividadUsada.getItemCount();
        for(int i=1;i<num;i++){
            cb_actividadUsada.removeItemAt(i);
        }
        
        for(Actividad act : actividadesTotales){
            
            cb_actividadUsada.addItem(act.getNombreActividad());
        }
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Costeo_ABC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Costeo_ABC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Costeo_ABC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Costeo_ABC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Costeo_ABC().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea at_reporte;
    private javax.swing.JButton bt_activarCalcular;
    private javax.swing.JButton bt_activarProducto;
    private javax.swing.JButton bt_asignarAProducto;
    private javax.swing.JButton bt_atras;
    private javax.swing.JButton bt_añadirProducto;
    private javax.swing.JButton bt_blockA;
    private javax.swing.JButton bt_blockAsignar;
    private javax.swing.JButton bt_calcular;
    private javax.swing.JButton bt_desBlockAsignar;
    private javax.swing.JButton bt_desblockA;
    private javax.swing.JButton bt_ingresarActividad;
    private javax.swing.JButton bt_reporte;
    private javax.swing.JComboBox<String> cb_actividadUsada;
    private javax.swing.JComboBox<String> cb_impulsadorUsado;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel jp_panelProducto;
    private javax.swing.JTextField txt_actividadCif;
    private javax.swing.JTextField txt_actividadNom;
    private javax.swing.JTextField txt_cantidadImpulsadorProducto;
    private javax.swing.JTextField txt_impulsadorActividad;
    private javax.swing.JTextField txt_impulsadorActividadCant;
    private javax.swing.JTextField txt_productoCosManoObra;
    private javax.swing.JTextField txt_productoCosMaterial;
    private javax.swing.JTextField txt_productoNom;
    private javax.swing.JTextField txt_productoUnidades;
    // End of variables declaration//GEN-END:variables
}

